[package]
name = "reductive"
version = "0.2.0"
edition = "2018"
authors = ["Daniël de Kok <me@danieldk.eu>"]
license = "Apache-2.0"
description = "Optimized vector quantization for dense vectors"
documentation = "https://docs.rs/reductive/"
homepage = "https://git.sr.ht/~danieldk/reductive"
repository = "https://git.sr.ht/~danieldk/reductive"

[dependencies]
ndarray = "0.12"
ndarray-parallel = "0.9"
num-traits = "0.2"
ordered-float = "1"
log = "0.4"
rand = "0.6"
rand_xorshift = "0.1"
rayon = "1"

ndarray-linalg = { version = "0.10", optional = true }

[dev-dependencies]
rand = "0.6"

[features]
default    = []
opq-train  = ["ndarray-linalg"]
accelerate = ["ndarray-linalg/accelerate"]
intel-mkl  = ["ndarray-linalg/intel-mkl"]
netlib     = ["ndarray-linalg/netlib"]
openblas   = ["ndarray-linalg/openblas"]