[package]
name = "reductive"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
ndarray = "0.12"
ndarray-linalg = "0.10"
ndarray-parallel = "0.9"
num-traits = "0.2"
ordered-float = "1"
log = "0.4"
rand = "0.6"
rand_xorshift = "0.1"
rayon = "1"

[dev-dependencies]
ndarray-rand = "0.9"
rand = "0.6"

[features]
default    = []
accelerate = ["ndarray-linalg/accelerate"]
intel-mkl  = ["ndarray-linalg/intel-mkl"]
netlib     = ["ndarray-linalg/netlib"]
openblas   = ["ndarray-linalg/openblas"]